llatrof/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

llatrof/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.category, name='category'),
    path('category/<str:category>/', views.category_goods, name='category_goods'),
    path('brand/', views.brand, name='brand'),
    path('brand/<str:brand>/', views.brand_goods, name='category_brand'),
    path('api/articles_list/', views.articles_list, name='articles_list'),
]

llatrof/llatrof/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views as articles_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.index),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

llatrof/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

llatrof/articles/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category = models.TextField(unique=True)

class Brand(models.Model):
    brand = models.TextField(unique=True)

class Article(models.Model):
    goods_url = models.TextField()
    goods_img_url = models.TextField()
    goods_category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE,
        db_column='goods_category',
        to_field='category',
    )
    goods_brand = models.ForeignKey(
        Brand, 
        on_delete=models.CASCADE,
        db_column='goods_brand',
        to_field='brand',
    )

llatrof/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', )

llatrof/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from .forms import CustomUserCreationForm

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

llatrof/articles/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Article
from .serializers import ArticleListSerializer

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

#######################################
#
# by. JaeHyeon (22/1O/26)
# category = goods_category 를 분류하기 위한 함수
# args ->
# categorise = Article Table 내 goods_category Field 를 중복 제거한 QuerySetList
# category_list = goods_category 만 분류한 List
#
#######################################
def category(request):
    categorise = Article.objects.values('goods_category').distinct()

    category_list = []
    for category in categorise:
        category = category['goods_category']
        category_list.append(category)

    context = {
        'category_list': category_list,
    }
    return render(request, 'articles/category.html', context)

#######################################
#
# by. JaeHyeon (22/1O/26)
# category_goods = category 기준으로 분류된 goods 만 rendering 하는 함수
# args ->
# goods_list = Article Table 내 goods_category 기준으로 variable routing 을 통해 받은 category(:str) 를 filtering 한 QuerySetList
#
#######################################
def category_goods(request, category):
    goods_list = Article.objects.all().filter(goods_category=category)
    
    context = {
        'goods_list': goods_list,
    }
    return render(request, 'articles/category.html', context)

#######################################
#
# by. JaeHyeon (22/1O/26)
# brand = goods_brand 를 분류하기 위한 함수
# args ->
# brands = Article Table 내 goods_brand Friled 를 중복 제거한 QuerySetList
# brands_list = goods_brand 만 분류한 List
#
#######################################
def brand(request):
    brands = Article.objects.values('goods_brand').distinct()
    brands_list = []
    for brand in brands:
        brand = brand['goods_brand']
        brands_list.append(brand)
    context = {
        'brands_list': brands_list,
    }
    return render(request, 'articles/brand.html', context)

#######################################
#
# by. JaeHyeon (22/1O/26)
# brand_goods = brand 기준으로 분류된 goods 만 rendering 하는 함수
# args ->
# goods_list = Article Table 내 goods_brand 기준으로 variable routing 을 통해 받은 brand(:str) 를 filtering 한 QuerySetList
#
#######################################
def brand_goods(request, brand):
    goods_list = Article.objects.all().filter(goods_brand=brand)
    
    context = {
        'goods_list': goods_list,
    }
    return render(request, 'articles/brand.html', context)

#######################################
#
# by. JaeHyeon (22/1O/26)
# articles_list = Serializing Article Records
#
#######################################
@api_view(['GET'])
def articles_list(request):
    articles = Article.objects.all()
    serializer = ArticleListSerializer(articles, many=True)
    return Response(serializer.data)

llatrof/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>SIGN UP</h1>

<form action="#" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>

{% endblock content %}

llatrof/articles/templates/articles/brand.html
<h1>Brand</h1>
<div>
    {% for brand in brands_list %}
        <li> 
            <a href="{% url 'articles:category_brand' brand %}">
            {{ brand }}
        </a> 
        </li>
    {% endfor %}
</div>

<div>
    {% for goods in goods_list %}
        <a href="{{ goods.goods_url }}">
            <img src="{{ goods.goods_img_url }}" alt="">
        </a>
    {% endfor %}
</div>

llatrof/articles/templates/articles/category.html
<h1>Category</h1>
<div>
    {% for category in category_list %}
        <li> 
            <a href="{% url 'articles:category_goods' category %}">
            {{ category }}
        </a> 
        </li>
    {% endfor %}
</div>

<div>
    {% for goods in goods_list %}
        <a href="{{ goods.goods_url }}">
            <img src="{{ goods.goods_img_url }}" alt="">
        </a>
    {% endfor %}
</div>

llatrof/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
<h1>INDEX</h1>
<div>
    {% for article in articles %}
        <a href="{{ article.goods_url }}">
            <img Class="zoom" src="{{ article.goods_img_url }}" >
        </a>
    {% endfor %}
</div>
{% endblock content %}

llatrof/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .zoom {
          transition: transform .2s;
        }
        
        .zoom:hover {
          transform: scale(2);
        }
    </style>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>